#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Directory whose available space is to be displayed
dir="${BLOCK_INSTANCE:-$HOME}";

#Color text red when less than 10% space is available
lowAlert=10; 

#Fetch directory space info
total=$(df -h -P -l "$dir" | tail -1 | awk '{print $2}' | tr -dc '0-9');
avail=$(df -h -P -l "$dir" | tail -1 | awk '{print $4}' | tr -dc '0-9');

#Display output
if (( $(( $avail*100/$total )) < $lowAlert )); then
	echo "<span foreground='red'>${avail}G</span>";
else
	echo "${avail}G";
fi
