#!/bin/bash

if [[ $(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo ok || echo error
) = "ok" ]]; then
	netStatus="Link Up";
else
	netStatus="Link Down";
fi

echo $netStatus