#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	1) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
esac

#Toggle mute
[[ $(pamixer --get-mute) = "true" ]] && echo -n 🔇 && exit
#Display volume
echo 🔊 $(pamixer --get-volume)%;
